coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default

ignore:
  - "dist/**"
  - "**/*.test.ts"
